#!/usr/bin/env python3
"""Regenerate the roster table in BENCHMARK.md from the benchmark manifest and our
game record, so the tier that governs replay access reflects the current build.

Sources, newest first:
  progress/games.csv    the scrimmage ladder (from 2026-09-17): one row per game,
                        `teamA`/`teamB` carry `us:<build>`, `winner` is A or B.
  progress/history.csv  optional, inherited from the predecessor project (its gauntlet era); absent here and skipped.

The tier uses the most recent SUBMISSION's record against that opponent (the latest build with at
least 200 recorded games: a candidate's 96-game ladder arm locked laurenschneider on 0 of 6, 2026-09-24), because tier
governs whether its replays may be read and an old rate would unlock the wrong ones.
Rewritten 2026-09-20: it read a `win_pct` column that history.csv has never had, so
it raised KeyError and the table had not been regenerated since `g_iter4`.
"""
import csv, re
from collections import defaultdict, OrderedDict
from pathlib import Path
REPO = Path(__file__).resolve().parent.parent
MANIFEST = Path.home() / "projects/vibe/bc24-benchmarks/manifest.tsv"

def tier(pct, prev_solved):
    if pct is None: return "untested"
    if pct < 20: return "locked"
    if pct < 50: return "target"
    if pct <= 90: return "peer"
    return "solved" if prev_solved else "peer(>90 once)"

def per_build():
    """{opponent: OrderedDict(build -> [wins, games])}, oldest build first."""
    out = defaultdict(OrderedDict)
    order = []
    hp = REPO / "progress" / "history.csv"
    if hp.is_file():
        for r in csv.DictReader(open(hp)):
            b = r.get("label") or "pre-ladder"
            if b not in order: order.append(b)
            e = out[r["opponent"]].setdefault(b, [0, 0])
            e[0] += int(r["wins"]); e[1] += int(r["total"])
    gp = REPO / "progress" / "games.csv"
    if gp.is_file():
        for r in csv.DictReader(open(gp)):
            a, b_ = r["teamA"], r["teamB"]
            if a.startswith("us:"): build, opp, side = a[3:], b_, "A"
            elif b_.startswith("us:"): build, opp, side = b_[3:], a, "B"
            else: continue
            if build not in order: order.append(build)
            e = out[opp].setdefault(build, [0, 0])
            e[1] += 1
            if r["winner"] == side: e[0] += 1
    rank = {b: i for i, b in enumerate(order)}
    for opp in out:
        out[opp] = OrderedDict(sorted(out[opp].items(), key=lambda kv: rank.get(kv[0], 0)))
    return out

SUBMISSION_GAMES = 200
def submissions(hist):
    """The builds with at least SUBMISSION_GAMES games in all: a candidate's short ladder arm never re-tiers the field."""
    totals = defaultdict(int)
    for opp in hist:
        for b, (w, g) in hist[opp].items(): totals[b] += g
    return {b for b, g in totals.items() if g >= SUBMISSION_GAMES}

def main():
    rows = list(csv.DictReader(open(MANIFEST), delimiter="\t"))
    hist = per_build(); subs = submissions(hist)
    lines = ["| opponent | repo (commit) | last win % | games | tier | history |",
             "|---|---|---|---|---|---|"]
    for r in sorted(rows, key=lambda r: (r["repo"], r["name"])):
        h = list(hist.get(r["name"], {}).items())
        hs = [kv for kv in h if kv[0] in subs] or h   # the tier: the latest submission's record (any build if none qualifies)
        last = hs[-1][1] if hs else None
        pct = 100.0 * last[0] / last[1] if last and last[1] else None
        prev = hs[-2][1] if len(hs) >= 2 else None
        prev_solved = bool(prev and prev[1] and 100.0 * prev[0] / prev[1] > 90)
        series = " ".join(f"{100.0*w/g:.0f}" for _, (w, g) in h if g)
        lines.append(f"| `{r['name']}` | {r['repo']} ({r['commit'][:7]}) | "
                     f"{pct:.0f} | {last[1]} | {tier(pct, prev_solved)} | {series} |"
                     if last else
                     f"| `{r['name']}` | {r['repo']} ({r['commit'][:7]}) | - | - | untested |  |")
    table = "\n".join(lines)
    p = REPO / "BENCHMARK.md"
    s = p.read_text()
    marker = "<!-- ROSTER TABLE: regenerated by tools/bench-roster.py -->"
    i = s.index(marker) + len(marker)
    # the table runs to the next heading, or to the trailing summary line if there is none
    j = s.find("\n## ", i)
    if j < 0:
        m = re.search(r"\n\n\d+ bot packages from \d+ repositories\.", s[i:])
        j = i + m.start() if m else len(s)
    repos = len({r["repo"] for r in rows})
    tail = f"\n\n{len(rows)} bot packages from {repos} repositories.\n"
    p.write_text(s[:i] + "\n\n" + table + tail)
    rated = sum(1 for r in rows if r["name"] in hist)
    print(f"roster table regenerated: {len(rows)} opponents, {rated} with a record")

if __name__ == "__main__":
    main()
