#!/usr/bin/env python3
# run with tools/.venv/bin/python3 on the driver (numpy, matplotlib live in the venv); post-block.sh does
"""Field score over time, projected to the end of the project's first and second weeks (PROMPTS 28-30, 46).
   tools/field-score.py [--outdir progress] [--tau 1.0]   -> field-score-1w.png (to the end of week 1) and field-score-4w.png (to week 4)

The field score (a build's expected score against every ladder bot, one game each) is a bounded percentage that
compresses as it rises, so it is not fitted directly. The RATING is: R(t) = R0 + a * ln(1 + t / tau), a
diminishing-returns curve (tau in days, default 1), weighted least squares over the submissions (g_iterN) with
weights 1 / SE^2, with a 95% band from the fit's covariance. The fitted and projected ratings are mapped to field
scores through elolib.field_score against the current ladder ratings, so the projection stays inside 0-100 by
construction. Every build is a point, dated by its first scrimmage block; candidates are shown hollow and are not
fitted. Regenerated by post-block.sh after every block, so the projection firms up as the record grows."""
import argparse, os, re, sys, datetime as dt
from zoneinfo import ZoneInfo
# PROMPTS 50 (2026-09-26): every time consideration is in the owner's timezone, PDT (America/Los_Angeles). Run ids are the
# machines' clock stamps (UTC); they are converted here. Times are naive PDT after conversion.
PDT = ZoneInfo('America/Los_Angeles'); UTC = dt.timezone.utc
def to_pdt(d): return d.replace(tzinfo=UTC).astimezone(PDT).replace(tzinfo=None)
import numpy as np
here = os.path.dirname(os.path.abspath(__file__)); repo = os.path.dirname(here)
sys.path.insert(0, here); import elolib
a = argparse.ArgumentParser(); a.add_argument('--outdir', default=os.path.join(repo, 'progress')); a.add_argument('--tau', type=float, default=1.0)
o = a.parse_args()
rows = elolib.load(); R, SE, games, wins = elolib.fit(rows); bots = elolib.ladder_bots()
first = {}
for r in rows:
    for b in (r['teamA'], r['teamB']):
        if elolib.is_ours(b):
            d = to_pdt(dt.datetime.strptime(r['run'][:15], '%Y%m%d-%H%M%S')); first[b] = min(first.get(b, d), d)
pts = sorted((first[p], p) for p in first if p in R and games.get(p, 0) >= 48)
subs = [(d, p) for d, p in pts if re.match(r'us:g_iter\d+$', p)]
if len(subs) < 2: sys.exit('fewer than two submissions to fit')
# A projection needs at least three submissions spanning half a day; before that the charts show only what was measured
# (2026-09-30: two builds an hour apart extrapolated to a rating of 26,000 by week 1).
t0 = subs[0][0]
def days(d): return (d - t0).total_seconds() / 86400
def score(r):
    R2 = dict(R); R2['proj'] = r; return 100 * elolib.field_score(R2, 'proj', bots)
rated = [b for b in bots if games.get(b, 0) > 0]
def rank_of(r):   # PROMPTS 78: 1 + the ladder bots rated above r (our other builds are not counted)
    return 1 + sum(1 for b in rated if R[b] > r)
def score_hi(r):   # PROMPTS 75: expected score against only the ladder bots rated above r (as ELO.md's "vs higher")
    up = [b for b in rated if R[b] > r]; R2 = dict(R); R2['proj'] = r
    return 100 * elolib.field_score(R2, 'proj', up) if up else float('nan')
FIT = len(subs) >= 3 and days(subs[-1][0]) >= 0.5
xs = np.array([np.log1p(days(d) / o.tau) for d, _ in subs]); ys = np.array([R[p] for _, p in subs]); w = np.array([1 / SE[p] for _, p in subs])
(aa, r0), cov = np.polyfit(xs, ys, 1, w=w, cov='unscaled') if FIT else ((0.0, ys[-1]), np.zeros((2, 2)))
def proj(t):
    x = np.log1p(t / o.tau); r = r0 + aa * x; s = np.sqrt(cov[0, 0] * x * x + 2 * cov[0, 1] * x + cov[1, 1]); return r, 1.96 * s
now = dt.datetime.now(PDT).replace(tzinfo=None); tn = days(now)
# The projection horizons are the ends of the project's weeks (PROMPTS 46: the project began 2026-09-30 (2024 season), so week 1 ends
# September 30), not "now + 7 days". PROMPTS 79: two charts, one to the end of week 1 and one to the end of week 4.
START = dt.datetime(2026, 9, 30); HORIZONS = [(f'week {k}', START + dt.timedelta(days=7 * k)) for k in (1, 2, 3, 4)]   # PDT
print('submissions:', ', '.join(f'{p[3:]} {R[p]:.0f}+-{1.96 * SE[p]:.0f} ({d:%m-%d %H:%M}) {score(R[p]):.1f}%' for d, p in subs))
print(f'rating fit R = {r0:.0f} + {aa:.0f} ln(1 + t/{o.tau:g} d) (t in days from {t0:%Y-%m-%d %H:%M} PDT)' if FIT else 'no projection yet (needs 3 submissions spanning half a day): measured points only')
r, e = proj(tn); print(f'  now ({now:%b %d}): rating {r:.0f} +- {e:.0f}  ->  field score {score(r):.1f}% [{score(r - e):.1f}%, {score(r + e):.1f}%], vs higher {score_hi(r):.1f}%, rank #{rank_of(r)}')
for name, when in (HORIZONS if FIT else []):
    r, e = proj(days(when)); print(f'  {name} ({when:%b %d}): rating {r:.0f} +- {e:.0f}  ->  field score {score(r):.1f}% [{score(r - e):.1f}%, {score(r + e):.1f}%], vs higher {score_hi(r):.1f}%, rank #{rank_of(r)}')
import matplotlib; matplotlib.use('Agg'); import matplotlib.pyplot as plt
def draw(weeks, path):
    HZ = HORIZONS[:weeks] if FIT else []
    fig, (ax1, ax2, ax3, ax4) = plt.subplots(4, 1, figsize=(9.5, 14.5), sharex=True)
    tt = np.linspace(0, days(HZ[-1][1]) + 0.3, 200) if FIT else np.array([]); dates = [t0 + dt.timedelta(days=t) for t in tt]
    rr = np.array([proj(t)[0] for t in tt]); ee = np.array([proj(t)[1] for t in tt])
    cand = [(d, p) for d, p in pts if (d, p) not in subs]
    # rating panel
    ax1.errorbar([d for d, _ in subs], ys, yerr=[1.96 * SE[p] for _, p in subs], fmt='o', color='tab:blue', ms=5, capsize=2, label='submission (rating +- 95%)', zorder=3)
    if cand: ax1.plot([d for d, _ in cand], [R[p] for _, p in cand], 'o', mfc='white', mec='tab:gray', ms=4, label='candidate (not fitted)')
    for d, p in cand: ax1.annotate(p[3:], (d, R[p]), textcoords='offset points', xytext=(4, -9), fontsize=6, color='0.4')
    for d, p in subs: ax1.annotate(p[3:], (d, R[p]), textcoords='offset points', xytext=(4, 5), fontsize=7)
    past = tt <= tn
    ax1.plot(np.array(dates)[past], rr[past], '-', color='tab:blue', lw=1.2, label=f'fit: R = {r0:.0f} + {aa:.0f} ln(1 + t/{o.tau:g}d)' if FIT else None)
    ax1.plot(np.array(dates)[~past], rr[~past], '--', color='tab:blue', lw=1.2, label='projection' if FIT else None); ax1.fill_between(dates, rr - ee, rr + ee, color='tab:blue', alpha=.12, label='95% band' if FIT else None)
    ax1.axvline(now, color='0.6', lw=0.8, ls=':'); ax1.set_ylabel('rating (Bradley-Terry, Elo scale)'); ax1.grid(alpha=.3); ax1.legend(fontsize=8, loc='lower right')
    ax1.set_title('Rating by submission with a diminishing-returns fit, and the field score it implies' if FIT else 'Rating by submission (projection starts once 3 submissions span half a day)')
    if not FIT: ax1.set_xlim(t0 - dt.timedelta(hours=1), max(now, subs[-1][0]) + dt.timedelta(hours=1))
    # field-score panel
    ss = np.array([score(r) for r in rr]); lo = np.array([score(r) for r in rr - ee]); hi = np.array([score(r) for r in rr + ee])
    ax2.plot([d for d, _ in subs], [score(R[p]) for _, p in subs], 'o', color='tab:blue', ms=5, zorder=3, label='submission')
    if cand: ax2.plot([d for d, _ in cand], [score(R[p]) for _, p in cand], 'o', mfc='white', mec='tab:gray', ms=4, label='candidate')
    ax2.plot(np.array(dates)[past], ss[past], '-', color='tab:blue', lw=1.2); ax2.plot(np.array(dates)[~past], ss[~past], '--', color='tab:blue', lw=1.2, label='projection (mapped rating)' if FIT else None)
    ax2.fill_between(dates, lo, hi, color='tab:blue', alpha=.12, label='95% band' if FIT else None)
    for name, d in HZ:
        r, e = proj(days(d)); ax2.plot([d], [score(r)], 's', color='tab:red', ms=6)
        ax2.annotate(f'{name} ({d:%b %d}): {score(r):.1f}% [{score(r - e):.0f}-{score(r + e):.0f}]', (d, score(r)), textcoords='offset points', xytext=(-8, 8), fontsize=8, ha='right', color='tab:red')
    ax2.axvline(now, color='0.6', lw=0.8, ls=':'); ax2.annotate('now', (now, ax2.get_ylim()[0]), textcoords='offset points', xytext=(3, 3), fontsize=7, color='0.4')
    ax2.set_ylabel('field score (%): expected score vs every ladder bot'); ax2.grid(alpha=.3); ax2.legend(fontsize=8, loc='lower right')
    # PROMPTS 75: the same, against only the ladder bots rated above the build (the set shrinks as the rating rises, so the
    # curve steps where a bot is passed)
    sh = np.array([score_hi(r) for r in rr])
    ax3.plot([d for d, _ in subs], [score_hi(R[p]) for _, p in subs], 'o', color='tab:purple', ms=5, zorder=3, label='submission')
    if cand: ax3.plot([d for d, _ in cand], [score_hi(R[p]) for _, p in cand], 'o', mfc='white', mec='tab:gray', ms=4, label='candidate')
    for d, p in subs: ax3.annotate(f"{p[3:]} ({sum(1 for b in rated if R[b] > R[p])})", (d, score_hi(R[p])), textcoords='offset points', xytext=(4, 5), fontsize=7)
    ax3.plot(np.array(dates)[past], sh[past], '-', color='tab:purple', lw=1.2); ax3.plot(np.array(dates)[~past], sh[~past], '--', color='tab:purple', lw=1.2, label='projection (mapped rating)' if FIT else None)
    for name, d in HZ:
        r, e = proj(days(d)); ax3.plot([d], [score_hi(r)], 's', color='tab:red', ms=6)
        ax3.annotate(f'{name}: {score_hi(r):.1f}% vs the {sum(1 for b in rated if R[b] > r)} above', (d, score_hi(r)), textcoords='offset points', xytext=(-8, 8), fontsize=8, ha='right', color='tab:red')
    ax3.axvline(now, color='0.6', lw=0.8, ls=':')
    ax3.set_ylabel('field score vs higher (%): only bots rated above'); ax3.grid(alpha=.3); ax3.legend(fontsize=8, loc='lower right')
    # PROMPTS 78: the rank among the ladder bots (1 = above them all), by submission, and along the fitted rating curve
    rk = np.array([rank_of(r) for r in rr]); rlo = np.array([rank_of(r) for r in rr + ee]); rhi = np.array([rank_of(r) for r in rr - ee])
    ax4.plot([d for d, _ in subs], [rank_of(R[p]) for _, p in subs], 'o', color='tab:green', ms=5, zorder=3, label='submission')
    if cand: ax4.plot([d for d, _ in cand], [rank_of(R[p]) for _, p in cand], 'o', mfc='white', mec='tab:gray', ms=4, label='candidate')
    for d, p in subs: ax4.annotate(f"{p[3:]} #{rank_of(R[p])}", (d, rank_of(R[p])), textcoords='offset points', xytext=(4, -10), fontsize=7)
    ax4.step(np.array(dates)[past], rk[past], '-', where='post', color='tab:green', lw=1.2); ax4.step(np.array(dates)[~past], rk[~past], '--', where='post', color='tab:green', lw=1.2, label='projection (mapped rating)' if FIT else None)
    ax4.fill_between(dates, rlo, rhi, step='post', color='tab:green', alpha=.12, label='95% band' if FIT else None)
    for name, d in HZ:
        r, e = proj(days(d)); ax4.plot([d], [rank_of(r)], 's', color='tab:red', ms=6)
        ax4.annotate(f'{name}: #{rank_of(r)} of {len(rated) + 1}', (d, rank_of(r)), textcoords='offset points', xytext=(-8, -14), fontsize=8, ha='right', color='tab:red')
    ax4.axvline(now, color='0.6', lw=0.8, ls=':'); ax4.invert_yaxis()
    ax4.set_ylabel(f'rank among the {len(rated)} ladder bots (1 = top)'); ax4.set_xlabel('first scrimmage block (PDT); (n) = bots above'); ax4.grid(alpha=.3); ax4.legend(fontsize=8, loc='lower right')
    fig.autofmt_xdate(); fig.tight_layout(); fig.savefig(path, dpi=120); plt.close(fig); print('wrote', path)

for weeks in (1, 4): draw(weeks, os.path.join(o.outdir, f'field-score-{weeks}w.png'))
