#!/usr/bin/env python3
"""Survey the tactics of every opponent across every kept replay of our scrimmage blocks.
   tools/tactics-survey.py [run-dir ...]   (default: every gauntlet/*scrim* dir)  -> progress/SURVEY.md, progress/survey.csv
One replay-dump --survey per game; the opponent's row and ours are kept. Per opponent: medians of the tactic
features and a list of the named tactics it shows (thresholds below), against our median in the same games."""
import csv, glob, io, os, subprocess, sys, statistics as st, collections
from concurrent.futures import ThreadPoolExecutor
HERE = os.path.dirname(os.path.abspath(__file__)); REPO = os.path.dirname(HERE)
runs = sys.argv[1:] or sorted(glob.glob(os.path.join(REPO, 'gauntlet', '*scrim*')))
files = [f for r in runs for f in glob.glob(os.path.join(r, 'losses', '*.bc24')) + glob.glob(os.path.join(r, 'replays', '*.bc24'))]
cache = os.path.join(REPO, 'progress', 'survey.csv')
done = {}
if os.path.exists(cache):
    for row in csv.DictReader(open(cache)): done.setdefault(row['file'], []).append(row)
def one(f):
    out = subprocess.run([os.path.join(HERE, 'replay-dump.sh'), f, '--survey'], capture_output=True, text=True).stdout
    rows = list(csv.DictReader(io.StringIO(out)))
    b = os.path.basename(f)[:-5]; opp = b.split('__')[0]; side = b.rsplit('bot', 1)[1]; build = os.path.basename(os.path.dirname(os.path.dirname(f))).split('scrim-')[-1]
    for r in rows: r.update(file=os.path.relpath(f, REPO), opp=opp, us=('1' if r['team'] == side else '0'), build=build)
    return rows
todo = [f for f in files if os.path.relpath(f, REPO) not in done]
with ThreadPoolExecutor(2) as ex:
    for rows in ex.map(one, todo):
        if rows: done[rows[0]['file']] = rows
allrows = [r for rs in done.values() for r in rs]
if allrows:
    with open(cache, 'w', newline='') as fh:
        w = csv.DictWriter(fh, fieldnames=list(allrows[0].keys())); w.writeheader(); w.writerows(allrows)
def num(x):
    try: return float(x)
    except (TypeError, ValueError): return None
def med(rs, k):
    v = [num(r[k]) for r in rs if num(r[k]) is not None]; return st.median(v) if v else float('nan')
TACTICS = [  # name, predicate on the per-opponent medians/rates
    ('moves flags in setup', lambda m: m['flagMoveDist'] >= 6),
    ('digs in setup (>=20)', lambda m: m['digs200'] >= 20),
    ('traps in setup (>=15)', lambda m: m['traps200'] >= 15),
    ('banks crumbs at r250 (>=1000)', lambda m: m['crumbs250'] >= 1000),
    ('explosive-heavy (>=10 by r400)', lambda m: m['expl400'] >= 10),
    ('water traps (>=3 by r400)', lambda m: m['water400'] >= 3),
    ('stun-heavy (>=60 by r400)', lambda m: m['stun400'] >= 60),
    ('fast raid (first pickup <= r260)', lambda m: 0 < m['firstPickup'] <= 260),
    ('relays carriers (drops >= 3)', lambda m: m['drops'] >= 3),
    ('guards flags (>=6 near at r300)', lambda m: m['defend300'] >= 6),
    ('heals more than it attacks by r400', lambda m: m['heal400'] > m['atk400'] > 0),
]
FEATS = ['flagMoveDist', 'digs200', 'traps200', 'crumbs250', 'expl400', 'water400', 'stun400', 'firstPickup', 'drops', 'defend300', 'atk400', 'heal400', 'level200', 'firstCapture']
by = collections.defaultdict(list)
for r in allrows: by[(r['opp'], r['us'])].append(r)
opps = sorted({o for o, u in by})
lines = ['# SURVEY.md — opponent tactics measured across every kept replay', '',
         f'{len(done)} games, {len(opps)} opponents (regenerated by `tools/tactics-survey.py`). Medians per opponent over all our builds\' games;',
         '"us" is our median in the same games. Tactic thresholds are in the script. Won = our win rate against it.', '',
         '| opponent | games | won | tactics it shows | ' + ' | '.join(FEATS) + ' |', '|' + '---|' * (4 + len(FEATS))]
counts = collections.Counter()
for o in sorted(opps, key=lambda o: sum(r['won'] == '1' for r in by[(o, '1')]) / max(1, len(by[(o, '1')]))):
    th, us = by.get((o, '0'), []), by.get((o, '1'), [])
    if not th: continue
    m = {k: med(th, k) for k in FEATS}; mu = {k: med(us, k) for k in FEATS}
    shown = [n for n, p in TACTICS if p(m)]
    for n in shown: counts[n] += 1
    won = sum(r['won'] == '1' for r in us) / max(1, len(us))
    lines.append(f'| {o} | {len(th)} | {100 * won:.0f}% | {"; ".join(shown)} | ' + ' | '.join(f'{m[k]:.0f} ({mu[k]:.0f})' for k in FEATS) + ' |')
lines += ['', '## How many opponents show each tactic', ''] + [f'- {n}: {c}' for n, c in counts.most_common()]
ours = [r for r in allrows if r['us'] == '1']
lines += ['', '## Our own medians over the same games', ''] + [f'- {k}: {med(ours, k):.0f}' for k in FEATS]
open(os.path.join(REPO, 'progress', 'SURVEY.md'), 'w').write('\n'.join(lines) + '\n')
# The measured section of TACTICS.md (owner standing order, PROMPTS 18): regenerated after every ladder block.
beaters = {o for o in opps if by.get((o, '1')) and sum(r['won'] == '1' for r in by[(o, '1')]) / len(by[(o, '1')]) <= 0.5}
sec = ['<!-- SURVEY:start (regenerated by tools/tactics-survey.py after every ladder block; edit the table above, not this) -->',
       '## Measured: which opponents use which tactic', '',
       f'From {len(done)} games against {len(opps)} opponents. "Beat us" = opponents we win at most half the games against '
       f'({len(beaters)}). "We do it" = our own median meets the same threshold. Details per opponent: `progress/SURVEY.md`.', '',
       '| tactic | opponents showing it | of which beat us | we do it | examples among those that beat us |', '|---|---|---|---|---|']
mus = {k: med(ours, k) for k in FEATS}
for n, p in TACTICS:
    show = [o for o in opps if by.get((o, '0')) and p({k: med(by[(o, '0')], k) for k in FEATS})]
    bs = [o for o in show if o in beaters]
    sec.append(f'| {n} | {len(show)} | {len(bs)} | {"yes" if p(mus) else "no"} | {", ".join(bs[:6])} |')
sec.append('<!-- SURVEY:end -->')
tp = os.path.join(REPO, 'TACTICS.md'); t = open(tp).read()
a, b = t.find('<!-- SURVEY:start'), t.find('<!-- SURVEY:end -->')
t = (t[:a] + '\n'.join(sec) + t[b + len('<!-- SURVEY:end -->'):]) if a >= 0 and b > a else (t.rstrip('\n') + '\n\n' + '\n'.join(sec) + '\n')
open(tp, 'w').write(t)
print('TACTICS.md measured section regenerated')
print('\n'.join(lines[-30:]))
